### PR TITLE
Use XPath for T_and_F_symbol_linter and fix false positives

### LINKED ISSUE #657: incorrectly tagged lint "Use FALSE instead of the symbol F"
Since a couple of days, I have started to get a new lint in my CI checks (https://github.com/IndrajeetPatil/statsExpressions/commit/cc00f65c4c6640c51cea165f6a557f13c097db85#commitcomment-44804914).

But I think this is unintentional, since here `F` refers to `F`-statistic

```r
R/helpers_anova.R:134:34: style: Use FALSE instead of the symbol F.

​        statistic = ez_df$ANOVA$F[2],

                                ~^
```

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #657

 - [x] implement fix
 - [x] add regression test
 - [x] add NEWS bullet

Migrating to XPath makes adding other exceptions easier as well.
Had to add the argument `offset` to `xml_nodes_to_lint` to keep the column numbers unchanged.

### CODE REVIEW

**Comment by AshesITR** [comment]
The `exclusions-test` also suffered from a #657 related false positive.
One of the eight lints was for the `F` in `F = T`.

**Comment by MichaelChirico** [comment]
> Don't use {T/F} as a variable name, as it can break code relying on {T/F} being {TRUE/FALSE}.

I agree with this (and have run into this issue before). FWIW, using T/F as variables is against the style guide due to conflicts with `base::T`/`base::F` (and the `T` case is specifically called out):

https://style.tidyverse.org/syntax.html#object-names

File: R/T_and_F_symbol_linter.R [hunk 1]
```diff
@@ -4,28 +4,55 @@
...
-            linter = "T_and_F_symbol_linter"
-          )
-        }
-      }
+    if (is.null(source_file$xml_parsed_content)) return(list())
+
+    xpath <- paste0(
+      "//SYMBOL[",
+      "(text() = 'T' or text() = 'F')", # T or F symbol
+      " and count(preceding-sibling::OP-DOLLAR) = 0", # not part of a $-subset expression
```
Comment (MichaelChirico) [inline R/T_and_F_symbol_linter.R:12]: `not(preceding-sibling::OP-DOLLAR)` is more "canonical XPath" to me (not that I have any real expertise to call XPath canonical :sweat_smile:)

File: R/T_and_F_symbol_linter.R [hunk 2]
```diff
@@ -4,28 +4,55 @@
...
+      " and count(parent::expr/following-sibling::LEFT_ASSIGN) = 0", # not target of left assignment
```
Comment (MichaelChirico) [inline R/T_and_F_symbol_linter.R:13]: `not(parent::expr[following::sibling::LEFT_ASSIGN or following-sibling::EQ_ASSIGN or preceding-sibling::RIGHT_ASSIGN])` would be better IMO

File: R/T_and_F_symbol_linter.R [hunk 3]
```diff
@@ -4,28 +4,55 @@
...
+      " and count(parent::expr/preceding-sibling::RIGHT_ASSIGN) = 0", # not target of right assignment
+      " and count(parent::expr/following-sibling::EQ_ASSIGN) = 0", # not target of equals assignment
+      "]"
+    )
+
+    xpath_assignment <- paste0(
+      "//SYMBOL[",
+      "(text() = 'T' or text() = 'F')", # T or F symbol
+      " and count(preceding-sibling::OP-DOLLAR) = 0", # not part of a $-subset expression
```
Comment (MichaelChirico) [inline R/T_and_F_symbol_linter.R:22]: similarly here:

```
[not(preceding-sibling::OP-DOLLAR) and parent::expr[following-sibling::LEFT_ASSIGN or ...]]
```

File: R/utils.R [hunk 4]
```diff
@@ -184,13 +184,14 @@ unescape <- function(str, q="`") {
 
 # convert an XML match into a Lint
 xml_nodes_to_lint <- function(xml, source_file, message, linter,
-                              type = c("style", "warning", "error")) {
+                              type = c("style", "warning", "error"),
+                              offset = 0L) {
```
Comment (MichaelChirico) [inline R/utils.R:188]: nice extension! eventually i think we can refactor a lot of the XPath lints to use this helper. Basically as long as `message` is static (e.g. this isn't the case for `seq_linter`) I think this can be used.

File: R/T_and_F_symbol_linter.R (hunk 1 above)
Comment (AshesITR) [reply R/T_and_F_symbol_linter.R:12]: Sounds more idiomatic than `count() = 0` 👍 
I'll change this later.

File: R/utils.R (hunk 4 above)
Comment (AshesITR) [reply R/utils.R:188]: Maybe we can even vectorize on message?
The T and F symbol linter needs a wrapper at the call site that just generates the proper message.

File: R/T_and_F_symbol_linter.R (hunk 3 above)
Comment (AshesITR) [reply R/T_and_F_symbol_linter.R]: I kept the OP-DOLLAR part the same to help see the parallels between the two XPath expressions.
They only differ in `and not(parent::expr[...])` vs. `and parent::expr[...]`

File: R/T_and_F_symbol_linter.R (hunk 2 above)
Comment (AshesITR) [reply R/T_and_F_symbol_linter.R]: Done

File: R/T_and_F_symbol_linter.R (hunk 1 above)
Comment (AshesITR) [reply R/T_and_F_symbol_linter.R]: Done

**Comment by AshesITR** [comment]
r-release CI failures are due to #761.

File: R/utils.R (hunk 4 above)
Comment (MichaelChirico) [reply R/utils.R:205]: Let's tuck this away to revisit for now

**Review by MichaelChirico — APPROVED** [review]
