### PR TITLE
Fix `package_hooks_linter` to validate `.onUnload()` arguments

### LINKED ISSUE #2940: package_hooks_linter should trigger on .onUnload without arguments
```r
lint(text = ".onUnload <- function() NULL", linters = package_hooks_linter())
# ℹ No lints found.
```

But such a hook triggers an `R CMD check` `WARNING`

```
* checking whether the namespace can be unloaded cleanly ... WARNING
---- unloading
Warning message:
.onUnload failed in unloadNamespace() for '${PKG}', details:
  call: fun(...)
  error: unused argument ("/tmp/Rtmp1ax8VR/${PKG}.Rcheck/${PKG}") 
```

### PR DESCRIPTION
**Pull request by emmanuel-ferdman**
## PR Summary
This PR fixes `package_hooks_linter` to properly validate `.onUnload()` hook signatures. Previously, the linter would silently ignore `.onUnload()` functions with missing or incorrect arguments, but `R CMD` check requires `.onUnload()` to take exactly one argument starting with 'lib' (like libpath). The fix adds `.onUnload` to the existing argument validation logic that was already checking `.onDetach()` and `.Last.lib()`.

R source reference for `.onUnload(libpath)`: https://github.com/wch/r-source/blob/97f6c68d5856ecc2257867e89bc870d7e49a8da8/src/library/base/R/namespace.R#L881-L892

Fixes #2940.

Related: #2737

### CODE REVIEW

File: tests/testthat/test-package_hooks_linter.R [hunk 1]
```diff
@@ -265,6 +288,16 @@ test_that("function shorthand is handled", {
     rex::rex(".onDetach() should take one argument starting with 'lib'."),
     linter
   )
+  expect_lint(
+    ".onUnload <- \\() { }",
+    rex::rex(".onUnload() should take one argument starting with 'lib'."),
+    linter
+  )
+  expect_lint(
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]: use expect_no_lint here

Comment (emmanuel-ferdman) [reply tests/testthat/test-package_hooks_linter.R]: Right, fixed 🙌

File: tests/testthat/test-package_hooks_linter.R [hunk 2]
```diff
@@ -195,14 +198,10 @@ test_that("package_hooks_linter catches usage of library.dynam.unload()", {
...
-  expect_lint(
-    ".onUnload <- function(lib) { library.dynam.unload() }",
-    NULL,
-    linter
-  )
+  expect_no_lint(".onUnload <- function(lib) { library.dynam.unload() }", linter)
 })
 
-test_that("package_hooks_linter detects bad argument names in .onDetach()/.Last.lib()", {
+test_that("package_hooks_linter detects bad argument names in .onDetach()/.Last.lib()/.onUnload()", {
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]:
```suggestion
test_that("package_hooks_linter detects bad argument names in 'teardown' hooks", {
```

File: tests/testthat/test-package_hooks_linter.R [hunk 3]
```diff
@@ -265,6 +284,12 @@ test_that("function shorthand is handled", {
     rex::rex(".onDetach() should take one argument starting with 'lib'."),
     linter
   )
+  expect_lint(
+    ".onUnload <- \\() { }",
+    rex::rex(".onUnload() should take one argument starting with 'lib'."),
+    linter
+  )
+  expect_no_lint(".onUnload <- \\(libpath) { }", linter)
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]:
```suggestion
```

File: tests/testthat/test-package_hooks_linter.R [hunk 4]
```diff
@@ -279,4 +298,16 @@ test_that("lints vectorize", {
...
+    trim_some("{
+      .onDetach <- function(xxx) { }
+      .onUnload <- function(yyy) { }
+    }"),
+    list(
+      list(".onDetach", line_number = 2L),
+      list(".onUnload", line_number = 3L)
+    ),
+    package_hooks_linter()
+  )
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]:
```suggestion
```

File: tests/testthat/test-package_hooks_linter.R [hunk 5]
```diff
@@ -279,4 +298,5 @@ test_that("lints vectorize", {
     ),
     package_hooks_linter()
   )
+
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]:
```suggestion
```

File: tests/testthat/test-package_hooks_linter.R [hunk 6]
```diff
@@ -171,14 +171,17 @@ test_that("package_hooks_linter blocks attaching namespaces", {
   )
 })
 
-test_that("package_hooks_linter skips valid .onDetach() and .Last.lib()", {
+test_that("package_hooks_linter skips valid .onDetach(), .Last.lib(), and .onUnload()", {
```
Comment (MichaelChirico) [inline tests/testthat/test-package_hooks_linter.R]:
```suggestion
test_that("package_hooks_linter skips valid 'teardown' hooks", {
```
