### PR TITLE
Throw a lint for missing Rmd chunk ends instead of an error

### LINKED ISSUE #571: Malformed file! message for imbalanced chunk gates is not helpful
```
writeLines("```{r chunk}
lm(x ~ y)
", tmp <- tempfile(fileext = '.Rmd'))
lintr::lint(tmp)
# Error: Malformed file!
```

This error message should be improved

### PR DESCRIPTION
**Pull request by AshesITR**
fixes #571

### CODE REVIEW

File: R/extract.R [hunk 1]
```diff
@@ -67,15 +72,22 @@ filter_chunk_end_positions <- function(starts, ends) {
...
-  code_ends <- positions[1 + code_start_indexes]
 
-  stopifnot(all(grepl("ends", names(code_ends))))
+  code_ends <- positions[pmin(1 + code_start_indexes, length(positions))]
+
+  bad_end_indexes <- which(grepl("starts", names(code_ends), fixed = TRUE))
+  if (length(bad_end_indexes)) {
+    bad_start_positions <- positions[code_start_indexes[bad_end_indexes]]
+    # This error message is formatted like a parse error
+    stop(sprintf(
```
Comment (MichaelChirico) [inline R/extract.R:85]: I recommend using `gettextf` here -- `lintr` doesn't do translations (yet) but if it does someday, it'll make it easier.

It's ~basically a drop-in replacement given that we're not doing translation. If we truly wanted to prepare for translation, we'd do `stop(domain=NA, gettextf(..., domain="R-linter"))`.

Not crucial but I think it's an easy change, WDYT?

File: R/extract.R [hunk 2]
```diff
@@ -67,15 +72,22 @@ filter_chunk_end_positions <- function(starts, ends) {
...
+      "<rmd>:%1$d:1: Missing chunk end for chunk (maybe starting at line %1$d).\n",
```
Comment (MichaelChirico) [inline R/extract.R:86]: Oh wow, TIL `sprintf` accepts the `%1$d` notation! Awesome.

File: R/extract.R (hunk 1 above)
Comment (AshesITR) [reply R/extract.R:85]: Sounds like a good idea for another issue.
The codebase contains 9 relevant occurences of `stop()`. I think we should migrate all of them at the same time.

File: R/extract.R (hunk 2 above)
Comment (AshesITR) [reply R/extract.R:86]: Yep, I find it very handy. #544 would have to deal with that BTW.

File: R/extract.R (hunk 1 above)
Comment (MichaelChirico) [reply R/extract.R:85]: Sounds good. Filed #577 so as not to forget. Also related: #530

File: R/extract.R (hunk 2 above)
Comment (MichaelChirico) [reply R/extract.R:86]: cc @renkun-ken

Comment (MichaelChirico) [reply R/extract.R:86]: @renkun-ken not sure if it would be helpful, but FYI Matt wrote some logic in C for handling `sprintf` fmts including handling the `%<pos>$<fmt>` notation:

https://github.com/Rdatatable/data.table/blob/master/src/snprintf.c

**Review by MichaelChirico — CHANGES_REQUESTED** [review]
Logic looks ~basically good at a glance -- please add some tests to confirm everything's working

**Comment by AshesITR** [comment]
I've added the two examples from our discussion as well as one with a trailing un-closed chunk (thats the reason for using `pmin()` in indexing)

NB that your example code, just as expected, isn't found to fail parsing because currently we don't detect all chunk begin / end tokens.
If we want to remain compatible with non-r code chunks and still catch this error, we'd have to parse all types of chunk boundaries and match them.

File: tests/testthat/test-knitr_formats.R [hunk 3]
```diff
@@ -104,9 +104,59 @@ test_that("it does _not_ error with inline \\Sexpr", {
...
+test_that("it does lint with malformed input", {
+  expect_lint(
+    file = "knitr_malformed/incomplete_r_block.Rmd",
+    checks = "Missing chunk end",
+    default_linters
+  )
+
+  contents <- c(
+    paste(
+      "```{r chunk}",
```
Comment (MichaelChirico) [inline tests/testthat/test-knitr_formats.R:116]: WDYT about putting an ad hoc file into a string like this

    contents <- "```{r chunk}
    lm(x ~ y)
    
    
    # some text
    
    ```
    bash some_script.sh
    ```
    "

more readable than being cluttered with `"` IMO

**Review by MichaelChirico — APPROVED** [review]
LGTM, great!

File: tests/testthat/test-knitr_formats.R (hunk 3 above)
Comment (AshesITR) [reply tests/testthat/test-knitr_formats.R:116]: Wouldn't the indentation be messed up either in the source code or in the ad hoc file?
Maybe a helper function that automatically detects the correct amount of trimming would produce nice code and nice ad-hoc files.

Something like

```r
if (lala) {
  ad_hoc <- trim_some("
    line1
    line2
      line3 indented
  ")
}
```

Which should produce the same value as
`ad_hoc <- "line1\nline2\n__line3 indented"` (double underscore instead of space to prevent github trimming)

Comment (MichaelChirico) [reply tests/testthat/test-knitr_formats.R:116]: The idea is for `trim_some` to trim relative to the first line? or I guess relative to the least-indented line. Looks good anyway, probably OK to just add such helper in `tests/testthat` only.

Comment (AshesITR) [reply tests/testthat/test-knitr_formats.R:116]: Exactly, relative to the least indented line. I guess I might as well add this in the current PR since travis had a random hiccup preventing merge.

**Review by MichaelChirico — DISMISSED** [review]

File: R/extract.R [hunk 4]
```diff
@@ -1,11 +1,16 @@
...
-extract_r_source <- function(filename, lines) {
+extract_r_source <- function(filename, lines, error = identity) {
   pattern <- get_knitr_pattern(filename, lines)
   if (is.null(pattern$chunk.begin) || is.null(pattern$chunk.end)) {
     return(lines)
   }
 
-  chunks <- get_chunk_positions(pattern = pattern, lines = lines)
+  chunks <- tryCatch(get_chunk_positions(pattern = pattern, lines = lines), error = error)
+  if (!inherits(chunks, "list")) {
```
Comment (MichaelChirico) [inline R/extract.R:9]: why not `is.list` here?

File: R/extract.R [hunk 5]
```diff
@@ -67,15 +72,22 @@ filter_chunk_end_positions <- function(starts, ends) {
...
-  }
 
   positions <- sort(c(starts = starts, ends = ends))
   code_start_indexes <- grep("starts", names(positions))
-  code_ends <- positions[1 + code_start_indexes]
 
-  stopifnot(all(grepl("ends", names(code_ends))))
+  code_ends <- positions[pmin(1 + code_start_indexes, length(positions))]
+
+  bad_end_indexes <- which(grepl("starts", names(code_ends), fixed = TRUE))
```
Comment (MichaelChirico) [inline R/extract.R:81]: `which(grepl(.))` is just `grep()` right?

**Review by MichaelChirico — DISMISSED** [review]
LGTM!

File: R/extract.R (hunk 4 above)
Comment (AshesITR) [reply R/extract.R:9]: just for consistency with L246 (implementation of get_source_file).
WDYT about switching both to `inherits(., "error")` instead? That seems more clear to me.

File: R/extract.R (hunk 5 above)
Comment (AshesITR) [reply R/extract.R:81]: Yep, totally overlooked. Thanks!

File: R/extract.R (hunk 4 above)
Comment (MichaelChirico) [reply R/extract.R]: agree, if we can make the branch `if(x)` instead of `if(!y)` that's always better IMO

**Review by MichaelChirico — APPROVED** [review]
