### PR TITLE
with_defaults removes newlines before processing names

### LINKED ISSUE #774: with_defaults breaks on long input
```
names(lintr::with_defaults(
  default = list(),
  lintr::undesirable_function_linter(c(
    detach = paste(
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    )
  ))
))
# [1] "lintr::undesirable_function_linter\n    \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\")))"
```

Obviously a bit contrived but actually got bit by this in a case where there are a few long comments intervening & several functions with long messages.

Something goes wrong with the `eval(substitute())` approach at some number of characters. The issue is surmountable but `\n` isn't caught by `.*` in `perl` regex (which is what `re_substitutes` is using).

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #774

### CODE REVIEW

File: R/zzz.R [hunk 1]
```diff
@@ -44,7 +44,12 @@ with_defaults <- function(..., default = default_linters) {
     # var[["foo"]]    => "foo"
     nms[missing] <- re_substitutes(
       re_substitutes(
-        re_substitutes(args, rex("(", anything), ""),
+        re_substitutes(
+          # Very long input might have newlines which are not caught
+          #  by . in a perl regex; see #774
+          gsub("\n", "", args, fixed = TRUE),
+          rex("(", anything), ""
+        ),
```
Comment (AshesITR) [inline R/zzz.R:52]: could we stick to one style of regex-ing?
`re_substitutes(..., options = "s")` will enable dotall / single-line mode so that the regex doesn't need fixing.

**Review by AshesITR — CHANGES_REQUESTED** [review]
Let's stick to one regex command.

File: R/zzz.R (hunk 1 above)
Comment (MichaelChirico) [reply R/zzz.R:52]: great! TIL

**Review by AshesITR — APPROVED** [review]
LGTM
