### PR TITLE
fixes #322: allows Rmd chunks using {lang} engine format

### LINKED ISSUE #322: Lint fails with Rmd chunks using {lang} engine format
This issue is related to #32, where lintr should ignore non-R chunks as it lints. `lintr` currently only ignores chunks that have the following chunk header: `{r engine = "LANG"}`, vs. the newer and now more common `{LANG}` Refer [here](https://rmarkdown.rstudio.com/authoring_knitr_engines.html), and the discussion on knitr issue #963 [here](https://github.com/yihui/knitr/issues/963).

Currently, if you use the `{LANG}` language engine syntax, `lintr` will do 2 things:

1. attempt to lint the chunk and throw an error for the user
2. not lint any R code after that chunk.

Below is a minimal reprex, using the .Rmd test case in `lintr` as a base and adding a chunk with `{python}`.

````
text <- c('# Test #

          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
          tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
          vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
          no sea takimata sanctus est Lorem ipsum dolor sit amet.
          
          ```{r}
          a = 1
```

          Test
          ====
          
          Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod
          tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At
          vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren,
          no sea takimata sanctus est Lorem ipsum dolor sit amet.
          
          ```{r}
          b <- function(x) {
          d = 1
          }
          
          ```
          
          ```{r engine="python"}
          a=[]
          
          a[0]=1
          ```
          
          ```{python}
          a=[]
          
          a[0]=1
          ```


​          
          ## Same code chunk as above, but lintr will not ouput this
          ```{r}
          
          b <- function(x) {
          d = 1
          }
          
          ```
          ')
  tmp <- tempfile()

  writeLines(text, tmp)

  lintr::lint(tmp)
````
The results of the lint are below:

image

The part of the code that would require an edit is [here](https://github.com/jimhester/lintr/blob/15fd8ee6685248b7f477c949c1e78dc13350cd15/R/extract.R#L31).

I _think_ the fix to this would involve adding another `&&` condition that checked that the chunk began with `r` and does NOT have `engine` following it. Or perhaps more simply, found any chunk that began with anything other than `r` and ignored it. Happy to try a fix on this and submit a PR if that would be useful.

### PR DESCRIPTION
**Pull request by russHyde**
Rmarkdown format allows the use of code blocks in the following format

~~~~
```{some_engine}
# not necessarily R syntax
foo = bar
```
~~~~

These blocks should be filtered out before linting the remaining R-code blocks.

A couple of python blocks were added to test.Rmd: one with R-like syntax and one with syntax that can't be parsed as R.

The function `defines_knitr_engine` was extracted from `extract_r_source` and extended. This tests for the presence of {r engine = some_engine} and {some_engine} in the start line of a code chunk. The names of valid engines are obtained from `knitr::knit_engines`

An unrelated, cosmetic change to `filter_chunk_end_positions` was made (which(grepl(...)) --> grep(...)).

### CODE REVIEW

File: R/extract.R [hunk 1]
```diff
@@ -68,13 +68,26 @@ filter_chunk_end_positions <- function(starts, ends) {
...
   stopifnot(all(grepl("ends", names(code_ends))))
   code_ends
 }
 
+defines_knitr_engine <- function(line) {
+  # "scala|python|bash|..."
+  engine_choices <- paste(names(knitr::knit_engines$get()), collapse = "|")
+
+  # Looks for {some_engine}, {some_engine label, ...} or {some_engine, ...}
+  bare_engine_pattern <- paste0("\\{(", engine_choices, ")[, }]")
```
Comment (jimhester) [inline R/extract.R]: please construct this pattern using rex, it would be something like

```r
rex::rex("{", or(names(knitr::knit_engines$get())), one_of("}", " ", ","))
```

Comment (russHyde) [reply R/extract.R]: No problem. I've modified that and pushed. Hadn't used `rex` before.

**Comment by russHyde** [comment]
Thanks again for a great package
