### PR TITLE
Fix handling zero-length variable name error

### LINKED ISSUE #566: lintr::lint fails with ``
If the code contains the following double backticks

```r
``
```

then `lintr::lint()` will fail:

```
> lintr::lint("``\n")                                                                                                     
Error in source_file$lines[[line_number]] : subscript out of bounds
Backtrace:
1: structure(list(filename = filename, line_number = as.integer(line_number), 
2: Lint(filename = source_file$filename, line_number = line_number, 
3: value[[3L]](cond)
4: tryCatchOne(expr, names, parentenv, handlers[[1L]])
5: tryCatchList(expr, classes, parentenv, handlers)
6: tryCatch(source_file$parsed_content <- parse(text = source_file$content, 
7: get_source_file(source_file, error = lint_error)
8: get_source_expressions(filename)
9: lintr::lint("``\n")
```

Parsing the text will produce the following error:

```
> parse(text = "``")                                                                                                      
Error in parse(text = "``") : attempt to use zero-length variable name
Backtrace:
1: parse(text = "``")
```

### PR DESCRIPTION
**Pull request by renkun-ken**
Closes #566.

This PR checks if the parse error message has a hint for the source code error and fixes the handling of `attempt to use zero-length variable name` error caused by empty variable names in the following cases:

```r
``
``()
''()
""()
fun(''=42)
fun(""=42)
fun(a=1,""=42)
```

When this error occurs, it searches the source code with a pattern that covers the above cases.

* [x] Fix handling of error
* [x] Test case

### CODE REVIEW

File: R/get_source_expressions.R [hunk 1]
```diff
@@ -81,6 +82,31 @@ get_source_expressions <- function(filename) {
           double_quotes, capture(name = "starting", anything), double_quotes))
 
       line_location <- re_matches(source_file$content, rex(message_info$starting), locations = TRUE)
+      line_location <- line_location[complete.cases(line_location), ]
+
+      if (nrow(line_location) == 0L) {
+        if (grepl("attempt to use zero-length variable name", e$message)) {
+          # empty symbol: ``, ``(), ''(), ""(), fun(''=42), fun(""=42)
+          loc <- re_matches(source_file$content,
+            "``|''\\s*\\(|\"\"\\s*\\(|\\(''\\s*=|\\(\"\"\\s*=", locations = TRUE)
```
Comment (AshesITR) [inline R/get_source_expressions.R:91]: I think we should stick to one type of regex specification in lintr.
Can you convert that to a `rex()` expression?

Comment (AshesITR) [reply R/get_source_expressions.R:91]: NB the location of the argument in a function call need not be the first, eg. `fun(a = 1, '' = 2)`.
I think a regex covering this as well should be ``` ``|(''|"")\s*\(|[(,]\s*=(''|``|"")```

Comment (renkun-ken) [reply R/get_source_expressions.R]: Yes, you are right. Thanks!

File: R/get_source_expressions.R [hunk 2]
```diff
@@ -81,6 +82,34 @@ get_source_expressions <- function(filename) {
           double_quotes, capture(name = "starting", anything), double_quotes))
 
       line_location <- re_matches(source_file$content, rex(message_info$starting), locations = TRUE)
+      line_location <- line_location[complete.cases(line_location), ]
+
+      if (nrow(line_location) == 0L) {
+        if (grepl("attempt to use zero-length variable name", e$message)) {
```
Comment (MichaelChirico) [inline R/get_source_expressions.R:88]: fixed=TRUE

File: tests/testthat/test-error.R [hunk 3]
```diff
@@ -42,4 +42,32 @@ test_that("returns the correct linting", {
...
+
+  expect_lint("``()",
+    rex("attempt to use zero-length variable name")
+  )
+
+  expect_lint("''()",
+    rex("attempt to use zero-length variable name")
+  )
+
+  expect_lint("\"\"()",
```
Comment (MichaelChirico) [inline tests/testthat/test-error.R:58]: nit: `'""'` was used in the source (and IMO is easier on the eyes), I would use that here too (e.g. `'""()'`)

**Comment by MichaelChirico** [comment]
LGTM! Nice PR

File: R/get_source_expressions.R (hunk 2 above)
Comment (renkun-ken) [reply R/get_source_expressions.R]: Yes, it's better.

File: tests/testthat/test-error.R (hunk 3 above)
Comment (renkun-ken) [reply tests/testthat/test-error.R:58]: So we don't have a policy to only allow one type of quotes? Then sure it is better.

Comment (MichaelChirico) [reply tests/testthat/test-error.R]: Somehow I thought the tidyverse rule was "use double quotes, unless using single quotes to avoid escaping single quotes", but I don't see it in the style guide actually.

However, `single_quotes_linter` in this package makes that distinction :smiley: 

https://github.com/jimhester/lintr/blob/master/R/single_quotes_linter.R#L8

Comment (renkun-ken) [reply tests/testthat/test-error.R]: Thanks!

**Comment by AshesITR** [comment]
codecov complains about the fallback to l1c1 if we fail to match anything.

That's fine by me.

**Comment by renkun-ken** [comment]
Any other comments?

**Review by AshesITR — DISMISSED** [review]

**Review by AshesITR — APPROVED** [review]
